/* ============================================================
   DATA.JS — All demo seed data for the prototype
   ============================================================ */

const AppData = {

  // ── Organization ─────────────────────────────────────────
  org: {
    name: 'ABC Campaign',
    campaign_env: 'Demo Campaign — Texas District',
    admin: 'Alex Rivera',
    plan: 'Professional',
    state: 'TX',
  },

  currentUser: {
    name: 'Alex Rivera',
    email: 'alex.rivera@abccampaign.org',
    role: 'Organization Admin',
    initials: 'AR',
    avatar_color: 'a',
  },

  // ── Contacts ─────────────────────────────────────────────
  contacts: [
    { id: 1,  first: 'Sarah',    last: 'Johnson',   phone: '+1 (512) 555-0142', city: 'Austin',      state: 'TX', campaign: 'Election Reminder — Austin', texter: 'Mike Torres',   status: 'replied',   last_msg: '2h ago', opted_out: false, updated: 'Aug 26', tags: ['Voter','High Priority'], notes: 'Confirmed plans to vote Tuesday.' },
    { id: 2,  first: 'Michael',  last: 'Smith',     phone: '+1 (713) 555-0283', city: 'Houston',     state: 'TX', campaign: 'GOTV — Houston South',       texter: 'Sarah Lee',     status: 'messaged',  last_msg: '3h ago', opted_out: false, updated: 'Aug 26', tags: ['Voter'], notes: '' },
    { id: 3,  first: 'James',    last: 'Anderson',  phone: '+1 (214) 555-0374', city: 'Dallas',      state: 'TX', campaign: 'Volunteer Recruitment',       texter: 'John Martinez', status: 'pending',   last_msg: 'Never',  opted_out: false, updated: 'Aug 25', tags: ['Volunteer'], notes: 'Interested in weekend shifts.' },
    { id: 4,  first: 'Emily',    last: 'Davis',     phone: '+1 (210) 555-0465', city: 'San Antonio', state: 'TX', campaign: 'Policy Survey — SA',          texter: 'Amy Chen',      status: 'assigned',  last_msg: 'Never',  opted_out: false, updated: 'Aug 25', tags: ['Survey'], notes: '' },
    { id: 5,  first: 'Robert',   last: 'Wilson',    phone: '+1 (512) 555-0556', city: 'Austin',      state: 'TX', campaign: 'Election Reminder — Austin', texter: 'Mike Torres',   status: 'replied',   last_msg: '1h ago', opted_out: false, updated: 'Aug 26', tags: ['Voter','Early Ballot'], notes: 'Already voted early.' },
    { id: 6,  first: 'Jessica',  last: 'Martinez',  phone: '+1 (713) 555-0647', city: 'Houston',     state: 'TX', campaign: 'GOTV — Houston South',       texter: 'Sarah Lee',     status: 'opted-out', last_msg: '5h ago', opted_out: true,  updated: 'Aug 26', tags: [], notes: 'Requested removal.' },
    { id: 7,  first: 'David',    last: 'Brown',     phone: '+1 (214) 555-0738', city: 'Dallas',      state: 'TX', campaign: 'Volunteer Recruitment',       texter: 'John Martinez', status: 'messaged',  last_msg: '4h ago', opted_out: false, updated: 'Aug 26', tags: ['Volunteer'], notes: '' },
    { id: 8,  first: 'Jennifer', last: 'Taylor',    phone: '+1 (512) 555-0829', city: 'Austin',      state: 'TX', campaign: 'Election Reminder — Austin', texter: 'Carlos Rivera', status: 'messaged',  last_msg: '2h ago', opted_out: false, updated: 'Aug 26', tags: ['Voter'], notes: '' },
    { id: 9,  first: 'Christopher','last': 'Thomas',phone: '+1 (210) 555-0910', city: 'San Antonio', state: 'TX', campaign: 'Policy Survey — SA',          texter: 'Lisa Park',     status: 'pending',   last_msg: 'Never',  opted_out: false, updated: 'Aug 24', tags: ['Survey'], notes: '' },
    { id: 10, first: 'Amanda',   last: 'Jackson',   phone: '+1 (512) 555-1001', city: 'Austin',      state: 'TX', campaign: 'Election Reminder — Austin', texter: 'Mike Torres',   status: 'replied',   last_msg: '30m ago',opted_out: false, updated: 'Aug 26', tags: ['Voter','Mobilizer'], notes: 'Offered to drive neighbors.' },
    { id: 11, first: 'Matthew',  last: 'Harris',    phone: '+1 (713) 555-1102', city: 'Houston',     state: 'TX', campaign: 'GOTV — Houston South',       texter: 'Amy Chen',      status: 'messaged',  last_msg: '6h ago', opted_out: false, updated: 'Aug 26', tags: ['Voter'], notes: '' },
    { id: 12, first: 'Ashley',   last: 'Martin',    phone: '+1 (214) 555-1293', city: 'Dallas',      state: 'TX', campaign: 'Volunteer Recruitment',       texter: 'Sarah Lee',     status: 'assigned',  last_msg: 'Never',  opted_out: false, updated: 'Aug 23', tags: [], notes: '' },
    { id: 13, first: 'Daniel',   last: 'Garcia',    phone: '+1 (512) 555-1384', city: 'Austin',      state: 'TX', campaign: 'Election Reminder — Austin', texter: 'John Martinez', status: 'messaged',  last_msg: '3h ago', opted_out: false, updated: 'Aug 26', tags: ['Voter'], notes: '' },
    { id: 14, first: 'Brittany', last: 'White',     phone: '+1 (210) 555-1475', city: 'San Antonio', state: 'TX', campaign: 'Policy Survey — SA',          texter: 'Carlos Rivera', status: 'replied',   last_msg: '1h ago', opted_out: false, updated: 'Aug 26', tags: ['Survey'], notes: 'Very engaged response.' },
    { id: 15, first: 'Joshua',   last: 'Lopez',     phone: '+1 (713) 555-1566', city: 'Houston',     state: 'TX', campaign: 'GOTV — Houston South',       texter: 'Lisa Park',     status: 'pending',   last_msg: 'Never',  opted_out: false, updated: 'Aug 22', tags: [], notes: '' },
    { id: 16, first: 'Megan',    last: 'Lee',       phone: '+1 (512) 555-1657', city: 'Austin',      state: 'TX', campaign: 'Election Reminder — Austin', texter: 'Mike Torres',   status: 'messaged',  last_msg: '5h ago', opted_out: false, updated: 'Aug 26', tags: ['Voter'], notes: '' },
    { id: 17, first: 'Andrew',   last: 'Robinson',  phone: '+1 (214) 555-1748', city: 'Dallas',      state: 'TX', campaign: 'Volunteer Recruitment',       texter: 'Amy Chen',      status: 'opted-out', last_msg: '7h ago', opted_out: true,  updated: 'Aug 26', tags: [], notes: '' },
    { id: 18, first: 'Lauren',   last: 'Walker',    phone: '+1 (512) 555-1839', city: 'Austin',      state: 'TX', campaign: 'Election Reminder — Austin', texter: 'Sarah Lee',     status: 'replied',   last_msg: '45m ago',opted_out: false, updated: 'Aug 26', tags: ['Voter','HV'], notes: 'High-value voter, very responsive.' },
    { id: 19, first: 'Kevin',    last: 'Hall',      phone: '+1 (210) 555-1920', city: 'San Antonio', state: 'TX', campaign: 'Policy Survey — SA',          texter: 'John Martinez', status: 'assigned',  last_msg: 'Never',  opted_out: false, updated: 'Aug 21', tags: [], notes: '' },
    { id: 20, first: 'Stephanie','last': 'Allen',   phone: '+1 (713) 555-2011', city: 'Houston',     state: 'TX', campaign: 'GOTV — Houston South',       texter: 'Carlos Rivera', status: 'messaged',  last_msg: '2h ago', opted_out: false, updated: 'Aug 26', tags: ['Voter'], notes: '' },
  ],

  // ── Campaigns ────────────────────────────────────────────
  campaigns: [
    {
      id: 1,
      name: 'Election Reminder — Austin District',
      contacts: 3842,
      assigned: 2611,
      sent: 2611,
      delivered: 2456,
      replies: 217,
      delivery_rate: 94.1,
      reply_rate: 8.3,
      progress: 68,
      status: 'active',
      created: 'Aug 18, 2026',
      template: 'Election Reminder',
      texters: ['Mike Torres', 'Sarah Lee', 'John Martinez'],
      sending_number: '+1 (512) 555-0182',
      description: 'GOTV outreach to registered voters in Austin Central and East districts.',
    },
    {
      id: 2,
      name: 'GOTV — Houston South',
      contacts: 2910,
      assigned: 1310,
      sent: 1310,
      delivered: 1219,
      replies: 143,
      delivery_rate: 93.1,
      reply_rate: 10.9,
      progress: 45,
      status: 'active',
      created: 'Aug 20, 2026',
      template: 'GOTV Outreach',
      texters: ['Amy Chen', 'Lisa Park'],
      sending_number: '+1 (713) 555-0293',
      description: 'Ground-up get-out-the-vote effort across Houston South precincts.',
    },
    {
      id: 3,
      name: 'Volunteer Recruitment — Dallas',
      contacts: 1200,
      assigned: 0,
      sent: 0,
      delivered: 0,
      replies: 0,
      delivery_rate: 0,
      reply_rate: 0,
      progress: 0,
      status: 'ready',
      created: 'Aug 22, 2026',
      template: 'Volunteer Ask',
      texters: ['John Martinez', 'Amy Chen'],
      sending_number: '+1 (214) 555-0184',
      description: 'Recruiting volunteers for Dallas field operations this weekend.',
    },
    {
      id: 4,
      name: 'Policy Survey — San Antonio',
      contacts: 980,
      assigned: 304,
      sent: 304,
      delivered: 289,
      replies: 78,
      delivery_rate: 95.1,
      reply_rate: 26.0,
      progress: 31,
      status: 'paused',
      created: 'Aug 15, 2026',
      template: 'Survey Invite',
      texters: ['Carlos Rivera', 'Lisa Park'],
      sending_number: '+1 (210) 555-0375',
      description: 'Gauging voter opinions on key policy priorities ahead of the election.',
    },
    {
      id: 5,
      name: 'Absentee Ballot Follow-up',
      contacts: 1550,
      assigned: 1550,
      sent: 1550,
      delivered: 1476,
      replies: 312,
      delivery_rate: 95.2,
      reply_rate: 20.1,
      progress: 100,
      status: 'completed',
      created: 'Aug 10, 2026',
      template: 'Follow-up',
      texters: ['Mike Torres', 'Sarah Lee', 'Carlos Rivera'],
      sending_number: '+1 (512) 555-0182',
      description: 'Follow-up with absentee ballot requestees to confirm receipt.',
    },
  ],

  // ── Templates ────────────────────────────────────────────
  templates: [
    {
      id: 1,
      name: 'Election Reminder',
      body: 'Hi {{first_name}}, this is {{texter_name}} with {{organization}}. Are you planning to vote this Tuesday? Polls are open 7am–7pm. Reply YES or NO. Text STOP to opt out.',
      campaigns_using: 1,
      last_updated: 'Aug 18, 2026',
      status: 'active',
      char_count: 158,
      has_mms: false,
    },
    {
      id: 2,
      name: 'GOTV Outreach',
      body: 'Hey {{first_name}}, it\'s {{texter_name}} from {{organization}}. Election Day is Tuesday, Nov 5! Your polling place is in {{city}}. Need a ride? Reply RIDE and we\'ll connect you. Text STOP to opt out.',
      campaigns_using: 1,
      last_updated: 'Aug 20, 2026',
      status: 'active',
      char_count: 191,
      has_mms: false,
    },
    {
      id: 3,
      name: 'Volunteer Ask',
      body: 'Hi {{first_name}}! I\'m {{texter_name}} with {{organization}}. We\'re looking for volunteers in {{city}} this weekend. Can you spare 3 hours? Reply YES and I\'ll send details! Text STOP to opt out.',
      campaigns_using: 1,
      last_updated: 'Aug 22, 2026',
      status: 'active',
      char_count: 193,
      has_mms: false,
    },
    {
      id: 4,
      name: 'Survey Invite',
      body: '{{first_name}}, this is {{texter_name}} from {{organization}}. We\'re conducting a quick 2-minute policy survey in {{state}}. Your voice matters! Reply YES to participate. Text STOP to opt out.',
      campaigns_using: 1,
      last_updated: 'Aug 15, 2026',
      status: 'active',
      char_count: 187,
      has_mms: false,
    },
    {
      id: 5,
      name: 'Follow-up',
      body: 'Hi {{first_name}}, just checking in — did you receive your absentee ballot? Reply YES, NO, or NEED HELP and I\'ll make sure you\'re set to vote. — {{texter_name}}, {{organization}}. Text STOP to opt out.',
      campaigns_using: 1,
      last_updated: 'Aug 10, 2026',
      status: 'active',
      char_count: 198,
      has_mms: false,
    },
  ],

  // ── Team ─────────────────────────────────────────────────
  team: [
    { id: 1, name: 'Alex Rivera',    email: 'alex.rivera@abccampaign.org',    role: 'admin',   campaigns: 5, status: 'active', last_active: 'Just now',    initials: 'AR', color: 'a' },
    { id: 2, name: 'Mike Torres',    email: 'mike.torres@abccampaign.org',    role: 'texter',  campaigns: 2, status: 'active', last_active: '12m ago',     initials: 'MT', color: 'b' },
    { id: 3, name: 'Sarah Lee',      email: 'sarah.lee@abccampaign.org',      role: 'texter',  campaigns: 2, status: 'active', last_active: '5m ago',      initials: 'SL', color: 'c' },
    { id: 4, name: 'John Martinez',  email: 'john.martinez@abccampaign.org',  role: 'texter',  campaigns: 2, status: 'active', last_active: '22m ago',     initials: 'JM', color: 'd' },
    { id: 5, name: 'Amy Chen',       email: 'amy.chen@abccampaign.org',       role: 'manager', campaigns: 3, status: 'active', last_active: '1h ago',      initials: 'AC', color: 'e' },
    { id: 6, name: 'Carlos Rivera',  email: 'carlos.rivera@abccampaign.org',  role: 'texter',  campaigns: 2, status: 'active', last_active: '8m ago',      initials: 'CR', color: 'f' },
    { id: 7, name: 'Lisa Park',      email: 'lisa.park@abccampaign.org',      role: 'texter',  campaigns: 2, status: 'active', last_active: '45m ago',     initials: 'LP', color: 'b' },
    { id: 8, name: 'Tom Bradley',    email: 'tom.bradley@abccampaign.org',    role: 'manager', campaigns: 1, status: 'inactive',last_active: '3 days ago',  initials: 'TB', color: 'c' },
  ],

  // ── Conversations ─────────────────────────────────────────
  conversations: [
    {
      id: 1,
      contact_id: 1,
      contact: 'Sarah Johnson',
      phone: '+1 (512) 555-0142',
      campaign: 'Election Reminder — Austin',
      texter: 'Mike Torres',
      unread: 1,
      last_message: 'Yes, I\'m planning to vote!',
      last_time: '30m ago',
      messages: [
        { dir: 'out', text: 'Hi Sarah, this is Mike with ABC Campaign. Are you planning to vote this Tuesday? Polls are open 7am–7pm.', time: '10:12 AM', sender: 'Mike Torres' },
        { dir: 'in',  text: 'Yes, I\'m planning to vote!', time: '10:44 AM', sender: 'Sarah Johnson' },
        { dir: 'out', text: 'That\'s great, Sarah! Your polling place is Travis County Expo Center. Do you need any information about what\'s on the ballot?', time: '10:46 AM', sender: 'Mike Torres' },
        { dir: 'in',  text: 'No I think I\'m all set, thanks for checking in!', time: '11:02 AM', sender: 'Sarah Johnson' },
        { dir: 'out', text: 'Perfect! Have a wonderful day and thank you for making your voice heard. 🗳️', time: '11:03 AM', sender: 'Mike Torres' },
      ],
    },
    {
      id: 2,
      contact_id: 5,
      contact: 'Robert Wilson',
      phone: '+1 (512) 555-0556',
      campaign: 'Election Reminder — Austin',
      texter: 'Mike Torres',
      unread: 0,
      last_message: 'Already voted early last week.',
      last_time: '1h ago',
      messages: [
        { dir: 'out', text: 'Hi Robert, this is Mike with ABC Campaign. Are you planning to vote this Tuesday?', time: '9:45 AM', sender: 'Mike Torres' },
        { dir: 'in',  text: 'Already voted early last week.', time: '10:02 AM', sender: 'Robert Wilson' },
        { dir: 'out', text: 'Wonderful! Thank you for voting early, Robert. Every vote counts!', time: '10:04 AM', sender: 'Mike Torres' },
      ],
    },
    {
      id: 3,
      contact_id: 10,
      contact: 'Amanda Jackson',
      phone: '+1 (512) 555-1001',
      campaign: 'Election Reminder — Austin',
      texter: 'Mike Torres',
      unread: 2,
      last_message: 'Can I get a ride to the polls?',
      last_time: '15m ago',
      messages: [
        { dir: 'out', text: 'Hi Amanda, this is Mike with ABC Campaign. Are you planning to vote this Tuesday? We can help with transportation!', time: '11:20 AM', sender: 'Mike Torres' },
        { dir: 'in',  text: 'Yes! Actually, can I get a ride to the polls? I don\'t have a car.', time: '11:47 AM', sender: 'Amanda Jackson' },
        { dir: 'in',  text: 'Also, can I bring my neighbor? She wants to vote too.', time: '11:48 AM', sender: 'Amanda Jackson' },
      ],
    },
    {
      id: 4,
      contact_id: 14,
      contact: 'Brittany White',
      phone: '+1 (210) 555-1475',
      campaign: 'Policy Survey — SA',
      texter: 'Carlos Rivera',
      unread: 0,
      last_message: 'Happy to participate!',
      last_time: '1h ago',
      messages: [
        { dir: 'out', text: 'Hi Brittany, I\'m Carlos from ABC Campaign. We\'re doing a short policy survey. Would you like to participate?', time: '10:00 AM', sender: 'Carlos Rivera' },
        { dir: 'in',  text: 'Happy to participate!', time: '10:15 AM', sender: 'Brittany White' },
        { dir: 'out', text: 'Great! What\'s the most important issue for you in this election — economy, healthcare, education, or public safety?', time: '10:16 AM', sender: 'Carlos Rivera' },
        { dir: 'in',  text: 'Definitely healthcare. My family has really struggled with medical costs.', time: '10:31 AM', sender: 'Brittany White' },
        { dir: 'out', text: 'Thank you so much for sharing that, Brittany. Your feedback helps shape our platform. We really appreciate it!', time: '10:32 AM', sender: 'Carlos Rivera' },
      ],
    },
    {
      id: 5,
      contact_id: 18,
      contact: 'Lauren Walker',
      phone: '+1 (512) 555-1839',
      campaign: 'Election Reminder — Austin',
      texter: 'Sarah Lee',
      unread: 1,
      last_message: 'Do you know if there\'s early voting tomorrow?',
      last_time: '45m ago',
      messages: [
        { dir: 'out', text: 'Hi Lauren! This is Sarah with ABC Campaign. Are you ready to vote this Tuesday?', time: '10:30 AM', sender: 'Sarah Lee' },
        { dir: 'in',  text: 'Yes! Do you know if there\'s early voting tomorrow?', time: '11:15 AM', sender: 'Lauren Walker' },
      ],
    },
  ],

  // ── Notifications ────────────────────────────────────────
  notifications: [
    { id: 1, type: 'reply',    title: 'Amanda Jackson replied',        desc: 'Can I get a ride to the polls? Also, can I bring my neighbor?', time: '15m ago', unread: true,  color: 'teal' },
    { id: 2, type: 'reply',    title: 'Lauren Walker replied',         desc: 'Do you know if there\'s early voting tomorrow?',               time: '45m ago', unread: true,  color: 'teal' },
    { id: 3, type: 'campaign', title: 'Campaign milestone reached',    desc: 'Election Reminder — Austin hit 2,500 messages sent.',          time: '1h ago',  unread: true,  color: 'blue' },
    { id: 4, type: 'warning',  title: '48 opt-outs today',            desc: 'GOTV — Houston South has a slightly elevated opt-out rate.',    time: '2h ago',  unread: false, color: 'amber' },
    { id: 5, type: 'success',  title: 'CSV Import complete',           desc: '10,214 contacts imported from texas_voters.csv.',              time: '3h ago',  unread: false, color: 'green' },
    { id: 6, type: 'system',   title: 'System maintenance scheduled',  desc: 'Brief maintenance window tonight 2:00–2:15 AM CT.',            time: '5h ago',  unread: false, color: 'gray' },
  ],

  // ── Audit Events ─────────────────────────────────────────
  audit_events: [
    { id: 1,  ts: 'Aug 26, 2026 11:48 AM', user: 'Alex Rivera',   org: 'ABC Campaign', event: 'CSV Imported',       resource: 'texas_voters.csv (10,214 rows)',   ip: '104.28.11.42',   status: 'success' },
    { id: 2,  ts: 'Aug 26, 2026 11:20 AM', user: 'Mike Torres',   org: 'ABC Campaign', event: 'Message Sent',       resource: 'Contact #1001 — Amanda Jackson',    ip: '98.142.66.14',   status: 'success' },
    { id: 3,  ts: 'Aug 26, 2026 10:55 AM', user: 'Sarah Lee',     org: 'ABC Campaign', event: 'Message Sent',       resource: 'Contact #1018 — Lauren Walker',     ip: '72.14.224.91',   status: 'success' },
    { id: 4,  ts: 'Aug 26, 2026 10:42 AM', user: 'Alex Rivera',   org: 'ABC Campaign', event: 'Campaign Paused',    resource: 'Policy Survey — San Antonio',        ip: '104.28.11.42',   status: 'warning' },
    { id: 5,  ts: 'Aug 26, 2026 10:15 AM', user: 'Amy Chen',      org: 'ABC Campaign', event: 'Campaign Created',   resource: 'Volunteer Recruitment — Dallas',     ip: '162.88.44.23',   status: 'success' },
    { id: 6,  ts: 'Aug 26, 2026 09:30 AM', user: 'Alex Rivera',   org: 'ABC Campaign', event: 'User Invited',       resource: 'tom.bradley@abccampaign.org',        ip: '104.28.11.42',   status: 'success' },
    { id: 7,  ts: 'Aug 26, 2026 09:12 AM', user: 'Jessica Martinez','org':'ABC Campaign',event:'Contact Opted Out',resource: 'Contact #6 — Jessica Martinez',      ip: 'System',         status: 'info'    },
    { id: 8,  ts: 'Aug 26, 2026 08:45 AM', user: 'Carlos Rivera', org: 'ABC Campaign', event: 'Login',             resource: 'Session initiated',                  ip: '50.17.88.102',   status: 'success' },
    { id: 9,  ts: 'Aug 25, 2026 05:30 PM', user: 'Alex Rivera',   org: 'ABC Campaign', event: 'Template Updated',  resource: 'Election Reminder',                   ip: '104.28.11.42',   status: 'success' },
    { id: 10, ts: 'Aug 25, 2026 03:14 PM', user: 'Amy Chen',      org: 'ABC Campaign', event: 'Texter Assigned',   resource: '112 contacts → Mike Torres',          ip: '162.88.44.23',   status: 'success' },
    { id: 11, ts: 'Aug 25, 2026 01:00 PM', user: 'John Martinez', org: 'ABC Campaign', event: 'Message Sent',      resource: 'Bulk send — 324 messages',            ip: '45.56.73.19',    status: 'success' },
    { id: 12, ts: 'Aug 24, 2026 04:22 PM', user: 'Alex Rivera',   org: 'ABC Campaign', event: 'Campaign Launched', resource: 'Election Reminder — Austin District',  ip: '104.28.11.42',   status: 'success' },
  ],

  // ── Platform Orgs (Admin view) ────────────────────────────
  platform_orgs: [
    { id: 1, name: 'ABC Campaign',        admin: 'Alex Rivera',    users: 8,  campaigns: 5, messages: 42800, status: 'active',   created: 'Jan 15, 2026' },
    { id: 2, name: 'Texas Democrats',     admin: 'Maria Gonzalez', users: 24, campaigns: 12,messages: 183400,status: 'active',   created: 'Dec 3, 2025'  },
    { id: 3, name: 'Austin For Progress', admin: 'Ben Harrison',   users: 6,  campaigns: 3, messages: 18200, status: 'active',   created: 'Mar 8, 2026'  },
    { id: 4, name: 'Houston Civic',       admin: 'Priya Nair',     users: 11, campaigns: 7, messages: 67300, status: 'active',   created: 'Feb 20, 2026' },
    { id: 5, name: 'Lone Star Outreach',  admin: 'Derek Mills',    users: 4,  campaigns: 2, messages: 9100,  status: 'inactive', created: 'May 1, 2026'  },
    { id: 6, name: 'DFW Action Network', admin: 'Tanya Brooks',   users: 16, campaigns: 8, messages: 94500, status: 'active',   created: 'Nov 12, 2025' },
  ],

  // ── Analytics chart data ──────────────────────────────────
  analytics: {
    weekly_labels: ['Aug 20', 'Aug 21', 'Aug 22', 'Aug 23', 'Aug 24', 'Aug 25', 'Aug 26'],
    sent:      [820,  940,  1102, 980,  1240, 1480, 2080],
    delivered: [771,  884,  1037, 921,  1167, 1392, 1958],
    failed:    [49,   56,   65,   59,   73,   88,   122],
    replies:   [68,   81,   97,   88,   118,  142,  217],
  },

  // ── CSV Import mock data ──────────────────────────────────
  csv_import: {
    filename: 'texas_voters.csv',
    total_rows: 10482,
    valid: 10214,
    duplicates: 182,
    invalid_phones: 64,
    missing_fields: 22,
    mappings: [
      { csv_col: 'First Name',  sys_field: 'first_name',   confidence: 99, locked: true  },
      { csv_col: 'Mobile',      sys_field: 'phone_number', confidence: 97, locked: false },
      { csv_col: 'Surname',     sys_field: 'last_name',    confidence: 96, locked: true  },
      { csv_col: 'Postal',      sys_field: 'zip_code',     confidence: 92, locked: false },
      { csv_col: 'City',        sys_field: 'city',         confidence: 99, locked: true  },
      { csv_col: 'State',       sys_field: 'state',        confidence: 98, locked: true  },
      { csv_col: 'Email',       sys_field: 'email',        confidence: 95, locked: false },
      { csv_col: 'District',    sys_field: 'custom_1',     confidence: 78, locked: false },
    ],
    errors: [
      { row: 14,   type: 'Invalid Phone', field: 'Mobile',    value: '512-BAD-NUMB', message: 'Cannot be parsed as a valid US phone number' },
      { row: 87,   type: 'Missing Field', field: 'First Name',value: '',             message: 'Required field is empty' },
      { row: 203,  type: 'Duplicate',     field: 'Mobile',    value: '+1 (512) 555-0142', message: 'Contact already exists in system' },
      { row: 344,  type: 'Invalid Phone', field: 'Mobile',    value: '00000000',     message: 'Not a valid US phone number' },
      { row: 512,  type: 'Missing Field', field: 'First Name',value: '',             message: 'Required field is empty' },
      { row: 891,  type: 'Duplicate',     field: 'Mobile',    value: '+1 (713) 555-0283', message: 'Contact already exists in system' },
    ],
  },

  // ── Texter queue ─────────────────────────────────────────
  texter_queue: [
    { id: 1, contact: { first: 'Sarah',    last: 'Johnson',   city: 'Austin',      state: 'TX', phone: '+1 (512) 555-0142', campaign: 'Election Reminder', status: 'Voter' }, message: 'Hi Sarah, this is Mike with ABC Campaign. Are you planning to vote this Tuesday? Polls open 7am–7pm. Text STOP to opt out.' },
    { id: 2, contact: { first: 'Robert',   last: 'Wilson',    city: 'Austin',      state: 'TX', phone: '+1 (512) 555-0556', campaign: 'Election Reminder', status: 'Voter' }, message: 'Hi Robert, this is Mike with ABC Campaign. Are you planning to vote this Tuesday? Polls open 7am–7pm. Text STOP to opt out.' },
    { id: 3, contact: { first: 'Amanda',   last: 'Jackson',   city: 'Austin',      state: 'TX', phone: '+1 (512) 555-1001', campaign: 'Election Reminder', status: 'Mobilizer' }, message: 'Hi Amanda, this is Mike with ABC Campaign. Are you planning to vote this Tuesday? We can help with transportation! Text STOP to opt out.' },
    { id: 4, contact: { first: 'Jennifer', last: 'Taylor',    city: 'Austin',      state: 'TX', phone: '+1 (512) 555-0829', campaign: 'Election Reminder', status: 'Voter' }, message: 'Hi Jennifer, this is Mike with ABC Campaign. Are you planning to vote this Tuesday? Polls open 7am–7pm. Text STOP to opt out.' },
    { id: 5, contact: { first: 'Megan',    last: 'Lee',       city: 'Austin',      state: 'TX', phone: '+1 (512) 555-1657', campaign: 'Election Reminder', status: 'Voter' }, message: 'Hi Megan, this is Mike with ABC Campaign. Are you planning to vote this Tuesday? Polls open 7am–7pm. Text STOP to opt out.' },
  ],

  // ── Chart colors ─────────────────────────────────────────
  chart_colors: {
    teal:   '#0d9488',
    teal_light: 'rgba(13,148,136,0.15)',
    blue:   '#3b82f6',
    blue_light: 'rgba(59,130,246,0.15)',
    green:  '#22c55e',
    green_light: 'rgba(34,197,94,0.15)',
    red:    '#ef4444',
    red_light: 'rgba(239,68,68,0.15)',
    amber:  '#f59e0b',
    gray:   '#94a3b8',
    purple: '#a855f7',
  },
};
